server:
  hostname: localhost
  port: ${PORT:8189}
  servlet:
    context-path: /
spring:
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName:
      org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
